"""
tools/web_search.py — Tavily Web Search Tool for Claude
========================================================
Provides two things:

  1. WEB_SEARCH_TOOL_DEFINITION — A Claude tool schema dict that tells
     Claude what the web_search tool does, what parameters it accepts,
     and which are required. This is passed in the `tools` parameter of
     every Anthropic API call that needs web search capability.

  2. execute_web_search() — The actual function that runs when Claude
     decides to call the web_search tool. It posts to the Tavily Search
     API and returns structured results back to Claude as a tool_result.

How Claude tool-use works (simplified):
  1. We call Claude with `tools=[WEB_SEARCH_TOOL_DEFINITION]`
  2. Claude responds with stop_reason="tool_use" and a tool_use block
     containing the tool name and its input arguments (e.g. {"query": "..."})
  3. We call execute_web_search(**tool_block.input)
  4. We send the result back to Claude as a tool_result message
  5. Claude reads the results and continues its response

Tavily API docs: https://docs.tavily.com/
"""

from __future__ import annotations

import httpx          # Async HTTP client (similar to requests but async)
from config import settings


# ---------------------------------------------------------------------------
# Claude Tool Definition
# ---------------------------------------------------------------------------

WEB_SEARCH_TOOL_DEFINITION = {
    # The tool name — Claude uses this to identify which tool it is calling.
    # Must match the name we check for in the tool_use response handler.
    "name": "web_search",

    # Human-readable description that Claude uses to decide WHEN to call
    # this tool. Be specific — Claude reads this to understand the tool's
    # purpose and determine if it's appropriate for the current task.
    "description": (
        "Search the web for current expense policy information. "
        "Use this to look up: GSA per diem rates by city and date, "
        "IRS standard mileage rates, typical taxi/rideshare fares for a route, "
        "or other travel reimbursement policy standards."
    ),

    # JSON Schema for the tool's input parameters.
    # Claude generates a JSON object that matches this schema when calling the tool.
    "input_schema": {
        "type": "object",
        "properties": {
            "query": {
                "type": "string",
                "description": (
                    "Specific search query. Examples: "
                    "'GSA per diem lodging rate Chicago IL October 2024', "
                    "'IRS standard mileage rate 2025', "
                    "'typical Uber fare JFK to Manhattan 2024'"
                ),
            },
            "max_results": {
                "type": "integer",
                "description": "Number of results to return (1-5).",
                "default": 3,
            },
            "allowed_domains": {
                "type": "array",
                "items": {"type": "string"},
                "description": (
                    "Restrict results to these domains for authoritative sources. "
                    "E.g. ['gsa.gov'] for per diem, ['irs.gov'] for mileage rates."
                ),
            },
        },
        # Only 'query' is required; the other params have defaults
        "required": ["query"],
    },
}


# ---------------------------------------------------------------------------
# Tavily API Executor
# ---------------------------------------------------------------------------

async def execute_web_search(
    query: str,
    max_results: int = 3,
    allowed_domains: list[str] | None = None,
) -> dict:
    """
    Call the Tavily Search API and return structured search results.

    This function is called whenever Claude chooses to use the web_search
    tool. The result is passed back to Claude as a tool_result message,
    allowing Claude to read the search results and use them in its response.

    Args:
        query:           The search query string (generated by Claude).
        max_results:     How many search results to return (clamped to 1–5).
        allowed_domains: Optional list of domains to restrict results to.
                         E.g. ["gsa.gov"] ensures only official GSA content.

    Returns:
        A dict with two keys:
          - "answer":  Tavily's extracted direct answer to the query (str)
          - "results": List of {title, url, content} dicts from top pages.
                       Content is capped at 800 chars to stay within token limits.

    Raises:
        httpx.HTTPStatusError: If the Tavily API returns a non-2xx status.
    """
    # Build the Tavily API request payload
    payload: dict = {
        "api_key": settings.tavily_api_key,
        "query": query,
        # Clamp max_results between 1 and 5 (Tavily's valid range)
        "max_results": min(max(1, max_results), 5),
        # "advanced" depth retrieves more content from each page
        "search_depth": "advanced",
        # Ask Tavily to extract a direct answer (not just URLs)
        "include_answer": True,
        # Skip raw HTML — we only need the extracted text content
        "include_raw_content": False,
    }

    # Add domain filter if specified (e.g., only return gsa.gov results)
    if allowed_domains:
        payload["include_domains"] = allowed_domains

    # Make the async HTTP POST request to Tavily
    # timeout=30s prevents hanging if Tavily is slow
    async with httpx.AsyncClient(timeout=30.0) as client:
        response = await client.post("https://api.tavily.com/search", json=payload)
        response.raise_for_status()   # Raise on 4xx/5xx responses
        data = response.json()

    # Return a clean, structured dict that Claude can easily parse.
    # We truncate content to 800 chars to avoid overwhelming Claude's context window.
    return {
        "answer": data.get("answer", ""),
        "results": [
            {
                "title":   r.get("title", ""),
                "url":     r.get("url", ""),
                "content": r.get("content", "")[:800],  # Truncate long page content
            }
            for r in data.get("results", [])
        ],
    }
